#!/usr/bin/perl
#
# Copyright (C) 2008 Arne Georg Gleditsch <lxr@linux.no>.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# The full GNU General Public License is included in this distribution
# in the file called COPYING.

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/lib";

use Getopt::Long;

use LXRng ROOT => $FindBin::Bin;
use LXRng::Context;

my $reset  = 0;
my $drop   = 0;
my $init   = 0;

GetOptions("reset" => \$reset,
	   "drop"  => \$drop,
	   "init"  => \$init)
    or die "Failed to parse options";

my $tree = $ARGV[0];
my $context = LXRng::Context->new('tree' => $tree)
    if $tree;

die "Usage: $0 <tree-id> [--init | --reset | --drop]\n"
    unless $context and ($reset or $drop or $init);

my $index   = $context->config->{'index'};
my $hash    = $context->config->{'search'};

if ($reset or $drop) {
    $index->drop_db();
    $hash->reset_db();
}
if ($reset or $init) {
    $index->init_db();
}

