#!/usr/bin/perl

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/lib";

use Getopt::Long;

use LXRng ROOT => $FindBin::Bin;
use LXRng::Context;

my $trees  = 0;

GetOptions("trees" => \$trees)
    or die "Failed to parse options";

my @configs =  LXRng::Context->read_config();

die("Unable to parse config") 
    unless ref($configs[0]) eq 'HASH';

if ($trees) {
    print(map { "$_\n" } sort keys %{$configs[0]});
}


#use Data::Dumper;
#warn Dumper(\@configs);
